import { Player } from '../entities/Player.js';
import { WaveManager } from './WaveManager.js';
import { Projectile } from '../spells/Projectile.js';
import { CONFIG } from '../config.js';
import { CollisionHandler } from './CollisionHandler.js';
import { ParticleManager } from './ParticleManager.js';
import { castSpell } from './GameActions.js';

export class GameState {
  constructor(canvasWidth, canvasHeight, seed = null, unlockedElementKeys = []) {
    this.width = canvasWidth;
    this.height = canvasHeight;
    this.centerX = canvasWidth / 2;
    this.centerY = canvasHeight / 2;

    // Track which elements are unlocked for this game session
    this.unlockedElementKeys = [...unlockedElementKeys];

    this.player = new Player(this.centerX, this.centerY, CONFIG.player.radius);
    // Initial setup for player spells and essence
    this.player.equipSpells([], [5, 0, 0, 0]);

    this.waveManager = new WaveManager(this.centerX, this.centerY, seed);
    this.enemies = [];
    this.projectiles = [];
    this.particles = [];
    this.aoeEffects = []; // transient AoE visual effects

    this.score = 0;
    this.paused = false;
    this.waveStartPending = false; // NEW: True when waiting for player to start wave
    this.gameOver = false; // NEW: Track if game is over
    this.onGameOver = null; // NEW: Callback when player dies

    // NEW: Game speed multiplier (affects enemy speed, projectile speed, DoT ticks, etc.)
    this.speedMultiplier = 1;

    // New: handlers for collision and particles
    this.collisionHandler = new CollisionHandler(this);
    this.particleManager = new ParticleManager(this);
    this.lastFocusReward = 0; // Track focus rewarded this wave

    this.seed = seed;
  }

  // NEW: Set the game speed multiplier
  setSpeedMultiplier(multiplier) {
    this.speedMultiplier = Math.max(0.1, multiplier);
  }

  unlockElement(elementKey) {
    if (!this.unlockedElementKeys.includes(elementKey)) {
      this.unlockedElementKeys.push(elementKey);
    }
  }

  update(dt) {
    if (this.paused || this.waveStartPending || this.gameOver) return;
    
    // Apply speed multiplier to delta time for all game mechanics
    const scaledDt = dt * this.speedMultiplier;
    
    this.updateAoEs(scaledDt);
    
    // Update wave manager
    this.waveManager.update(scaledDt);

    // Spawn new wave if needed
    if (this.waveManager.waveActive && this.enemies.length === 0) {
      this.enemies = this.waveManager.spawnWave();
      // notify HUD of enemy count for the new wave
      try {
        if (window && window.gameInstance && window.gameInstance.hud) {
          window.gameInstance.hud.setEnemies(this.enemies.length);
          window.gameInstance.hud.setWave(this.waveManager.currentWave);
        }
      } catch (e) { /* silent */ }
    }

    // Update player and check for casting
    const readySlots = this.player.update(scaledDt);
    if (readySlots) {
      for (const slotIndex of readySlots) {
        castSpell(this, slotIndex);
      }
    }

    // Update knockback on enemies
    for (const enemy of this.enemies) {
      if (enemy.knockbackTimer && enemy.knockbackTimer > 0) {
        enemy.knockbackTimer -= scaledDt;
        enemy.x += enemy.knockbackVx * scaledDt;
        enemy.y += enemy.knockbackVy * scaledDt;
        
        // Apply friction
        enemy.knockbackVx *= 0.85;
        enemy.knockbackVy *= 0.85;
      }
    }

    // Update enemies
    for (const enemy of this.enemies) {
      enemy.update(scaledDt, this.centerX, this.centerY);
      // Collect particles generated by DoT ticks during update
      if (enemy.particleRequests.length > 0) {
        this.particles.push(...enemy.particleRequests);
        enemy.particleRequests.length = 0; // Clear requests after collection
      }
    }

    // Check for enemies reaching center and damage player
    const enemiesToRemove = [];
    for (let i = 0; i < this.enemies.length; i++) {
      const enemy = this.enemies[i];
      if (!enemy.alive) continue;
      
      const dx = enemy.x - this.centerX;
      const dy = enemy.y - this.centerY;
      const dist = Math.sqrt(dx * dx + dy * dy);
      
      // If enemy reaches center (within a small radius), damage player
      if (dist < enemy.type.width / 2 + this.player.radius) {
        this.player.hp -= 10;
        enemiesToRemove.push(i);
        
        // Update HUD
        try {
          if (window && window.gameInstance && window.gameInstance.hud) {
            window.gameInstance.hud.setHealth(this.player.hp);
          }
        } catch (e) { /* silent */ }
        
        // Check if player is dead
        if (this.player.hp <= 0) {
          this.gameOver = true;
          if (this.onGameOver) {
            this.onGameOver();
          }
          return;
        }
      }
    }
    
    // Remove enemies that reached center (in reverse order to maintain indices)
    for (let i = enemiesToRemove.length - 1; i >= 0; i--) {
      const idx = enemiesToRemove[i];
      // Mark as dead and flag it so later cleanup won't count it again.
      this.enemies[idx].alive = false;
      this.enemies[idx]._defeatedCounted = true; // custom flag to avoid double-counting
      // Count this enemy as defeated for the wave manager now (only once).
      this.waveManager.enemyDefeated();
    }

    // Update projectiles and collect trail particles
    for (const projectile of this.projectiles) {
      const trailParticles = projectile.update(scaledDt, this.enemies, this.width, this.height);
      if (trailParticles) {
        this.particles.push(...trailParticles);
      }
    }

    // Check collisions (delegated)
    this.collisionHandler.checkCollisions();

    // Remove dead entities
    this.projectiles = this.projectiles.filter(p => p.alive);
    // Only call waveManager.enemyDefeated() and give score for enemies that haven't already been counted.
    this.enemies = this.enemies.filter(e => {
      if (!e.alive) {
        if (!e._defeatedCounted) {
          this.waveManager.enemyDefeated();
          this.score += 10;
        }
        // notify HUD of score and decreased enemy count
        try {
          if (window && window.gameInstance && window.gameInstance.hud) {
            window.gameInstance.hud.setScore(this.score);
            // enemies array hasn't been filtered yet in caller contexts, but we can decrement current tracked count
            const remaining = Math.max(0, this.enemies.length - 1);
            window.gameInstance.hud.setEnemies(remaining);
          }
        } catch (e) { /* silent */ }
        return false;
      }
      return true;
    });
  }

  // NEW: Signal that the player is ready to start the current wave
  startWave() {
    this.waveStartPending = false;
    this.waveManager.waveActive = true;
  }

  // NEW: Prepare to show wave start button (pause wave spawning)
  showWaveStart() {
    this.waveStartPending = true;
  }

  createParticles(x, y, color) {
    this.particleManager.createParticles(x, y, color);
  }

  updateParticles(dt) {
    // Use scaled dt for particles too
    this.particleManager.updateParticles(dt * this.speedMultiplier);
  }

  updateAoEs(dt) {
    if (!this.aoeEffects) return;
    for (const aoe of this.aoeEffects) {
      aoe.life -= dt;
    }
    this.aoeEffects = this.aoeEffects.filter(a => a.life > 0);
  }

  createAoEVisual(x, y, radius, color, duration = 0.6) {
    this.aoeEffects.push({ x, y, radius, color, life: duration, maxLife: duration });
  }

  pause() {
    this.paused = true;
  }

  resume() {
    this.paused = false;
  }
}