import { Player } from '../entities/Player.js';
import { WaveManager } from './WaveManager.js';
import { Projectile } from '../spells/Projectile.js';
import { CONFIG } from '../config.js';
import { CollisionHandler } from './CollisionHandler.js';
import { ParticleManager } from './ParticleManager.js';
import { castSpell } from './GameActions.js';

export class GameState {
  constructor(canvasWidth, canvasHeight, seed = null, unlockedElementKeys = []) {
    this.width = canvasWidth;
    this.height = canvasHeight;
    this.centerX = canvasWidth / 2;
    this.centerY = canvasHeight / 2;

    // Track which elements are unlocked for this game session
    this.unlockedElementKeys = [...unlockedElementKeys];

    this.player = new Player(this.centerX, this.centerY, CONFIG.player.radius);
    // Initial setup for player spells and essence
    this.player.equipSpells([], [5, 0, 0, 0]);

    this.waveManager = new WaveManager(this.centerX, this.centerY, seed);
    this.enemies = [];
    this.projectiles = [];
    this.particles = [];
    this.aoeEffects = []; // transient AoE visual effects

    this.score = 0;
    this.paused = false;
    this.waveStartPending = false; // NEW: True when waiting for player to start wave

    // New: handlers for collision and particles
    this.collisionHandler = new CollisionHandler(this);
    this.particleManager = new ParticleManager(this);
    this.lastFocusReward = 0; // Track focus rewarded this wave

    this.seed = seed;
  }

  unlockElement(elementKey) {
    if (!this.unlockedElementKeys.includes(elementKey)) {
      this.unlockedElementKeys.push(elementKey);
    }
  }

  update(dt) {
    if (this.paused || this.waveStartPending) return;
    
    this.updateAoEs(dt);
    
    // Update wave manager
    this.waveManager.update(dt);

    // Spawn new wave if needed
    if (this.waveManager.waveActive && this.enemies.length === 0) {
      this.enemies = this.waveManager.spawnWave();
      // notify HUD of enemy count for the new wave
      try {
        if (window && window.gameInstance && window.gameInstance.hud) {
          window.gameInstance.hud.setEnemies(this.enemies.length);
          window.gameInstance.hud.setWave(this.waveManager.currentWave);
        }
      } catch (e) { /* silent */ }
    }

    // Update player and check for casting
    const readySlots = this.player.update(dt);
    if (readySlots) {
      for (const slotIndex of readySlots) {
        castSpell(this, slotIndex);
      }
    }

    // Update knockback on enemies
    for (const enemy of this.enemies) {
      if (enemy.knockbackTimer && enemy.knockbackTimer > 0) {
        enemy.knockbackTimer -= dt;
        enemy.x += enemy.knockbackVx * dt;
        enemy.y += enemy.knockbackVy * dt;
        
        // Apply friction
        enemy.knockbackVx *= 0.85;
        enemy.knockbackVy *= 0.85;
      }
    }

    // Update enemies
    for (const enemy of this.enemies) {
      enemy.update(dt, this.centerX, this.centerY);
      // Collect particles generated by DoT ticks during update
      if (enemy.particleRequests.length > 0) {
        this.particles.push(...enemy.particleRequests);
        enemy.particleRequests.length = 0; // Clear requests after collection
      }
    }

    // Update projectiles and collect trail particles
    for (const projectile of this.projectiles) {
      const trailParticles = projectile.update(dt, this.enemies, this.width, this.height);
      if (trailParticles) {
        this.particles.push(...trailParticles);
      }
    }

    // Check collisions (delegated)
    this.collisionHandler.checkCollisions();

    // Remove dead entities
    this.projectiles = this.projectiles.filter(p => p.alive);
    this.enemies = this.enemies.filter(e => {
      if (!e.alive) {
        this.waveManager.enemyDefeated();
        this.score += 10;
        // notify HUD of score and decreased enemy count
        try {
          if (window && window.gameInstance && window.gameInstance.hud) {
            window.gameInstance.hud.setScore(this.score);
            // enemies array hasn't been filtered yet in caller contexts, but we can decrement current tracked count
            const remaining = Math.max(0, this.enemies.length - 1);
            window.gameInstance.hud.setEnemies(remaining);
          }
        } catch (e) { /* silent */ }
        return false;
      }
      return true;
    });
  }

  // NEW: Signal that the player is ready to start the current wave
  startWave() {
    this.waveStartPending = false;
    this.waveManager.waveActive = true;
  }

  // NEW: Prepare to show wave start button (pause wave spawning)
  showWaveStart() {
    this.waveStartPending = true;
  }

  createParticles(x, y, color) {
    this.particleManager.createParticles(x, y, color);
  }

  updateParticles(dt) {
    this.particleManager.updateParticles(dt);
  }

  updateAoEs(dt) {
    if (!this.aoeEffects) return;
    for (const aoe of this.aoeEffects) {
      aoe.life -= dt;
    }
    this.aoeEffects = this.aoeEffects.filter(a => a.life > 0);
  }

  createAoEVisual(x, y, radius, color, duration = 0.6) {
    this.aoeEffects.push({ x, y, radius, color, life: duration, maxLife: duration });
  }

  pause() {
    this.paused = true;
  }

  resume() {
    this.paused = false;
  }
}