export const UNUSUAL_ELEMENTS = {
  ironwood: {
    name: 'Ironwood',
    color: { r: 110, g: 100, b: 80 },
    secondaryColor: { r: 140, g: 120, b: 100 },
    accentColor: { r: 160, g: 140, b: 110 },
    propertyGenes: {
      speed: 180,
      damage: 28,
      piercing: 5,
      knockback: 4,
      aoe: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 5,
      trailSize: 3,
      aura: true,
      auraSize: 23,
      auraIntensity: 0.5,
      impactParticles: 22,
      impactType: 'spark',
      sizeMultiplier: 1.08,
    },
    rarity: 'unusual'
  },

  pollen: {
    name: 'Pollen',
    color: { r: 220, g: 200, b: 80 },
    secondaryColor: { r: 240, g: 220, b: 100 },
    accentColor: { r: 200, g: 180, b: 60 },
    propertyGenes: {
      speed: 240,
      damage: 16,
      wave: 6,
      aoe: 5,
      dot: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 8,
      trailSize: 2,
      aura: true,
      auraSize: 26,
      auraIntensity: 0.45,
      impactParticles: 20,
      impactType: 'aura',
      randomColors: true,
      sizeMultiplier: 0.92,
    },
    rarity: 'unusual'
  },

  thorn: {
    name: 'Thorn',
    color: { r: 140, g: 100, b: 60 },
    secondaryColor: { r: 160, g: 120, b: 80 },
    accentColor: { r: 180, g: 140, b: 100 },
    propertyGenes: {
      speed: 220,
      damage: 30,
      piercing: 7,
      knockback: 3,
      wave: 2,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 4,
      trailSize: 3,
      aura: false,
      impactParticles: 24,
      impactType: 'spark',
      sizeMultiplier: 1.05,
    },
    rarity: 'unusual'
  },

  lotus: {
    name: 'Lotus',
    color: { r: 200, g: 150, b: 200 },
    secondaryColor: { r: 220, g: 180, b: 220 },
    accentColor: { r: 180, g: 120, b: 180 },
    propertyGenes: {
      speed: 200,
      damage: 18,
      aoe: 6,
      homing: 5,
      slowing: 4,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 7,
      trailSize: 2,
      aura: true,
      auraSize: 28,
      auraIntensity: 0.55,
      impactParticles: 20,
      impactType: 'swirl',
      shimmer: true,
      sizeMultiplier: 1.02,
    },
    rarity: 'unusual'
  },

  jade: {
    name: 'Jade',
    color: { r: 100, g: 160, b: 120 },
    secondaryColor: { r: 120, g: 180, b: 140 },
    accentColor: { r: 80, g: 140, b: 100 },
    propertyGenes: {
      speed: 190,
      damage: 26,
      piercing: 4,
      aoe: 4,
      chaining: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 5,
      trailSize: 2,
      aura: true,
      auraSize: 24,
      auraIntensity: 0.48,
      impactParticles: 18,
      impactType: 'spark',
      shimmer: true,
      sizeMultiplier: 1.0,
    },
    rarity: 'unusual'
  },

  pearl: {
    name: 'Pearl',
    color: { r: 230, g: 230, b: 240 },
    secondaryColor: { r: 240, g: 240, b: 250 },
    accentColor: { r: 200, g: 200, b: 220 },
    propertyGenes: {
      speed: 250,
      damage: 20,
      piercing: 6,
      wave: 5,
      homing: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'beam',
      trailDensity: 6,
      trailSize: 2,
      aura: true,
      auraSize: 22,
      auraIntensity: 0.52,
      impactParticles: 18,
      impactType: 'spark',
      shimmer: true,
      sizeMultiplier: 0.96,
    },
    rarity: 'unusual'
  },

  quartz: {
    name: 'Quartz',
    color: { r: 200, g: 200, b: 220 },
    secondaryColor: { r: 220, g: 220, b: 240 },
    accentColor: { r: 180, g: 180, b: 200 },
    propertyGenes: {
      speed: 210,
      damage: 22,
      splitting: 5,
      piercing: 3,
      wave: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 6,
      trailSize: 2,
      aura: true,
      auraSize: 20,
      auraIntensity: 0.45,
      impactParticles: 20,
      impactType: 'spark',
      shimmer: true,
      sizeMultiplier: 0.98,
    },
    rarity: 'unusual'
  },

  lava: {
    name: 'Lava',
    color: { r: 255, g: 80, b: 20 },
    secondaryColor: { r: 255, g: 120, b: 40 },
    accentColor: { r: 255, g: 150, b: 60 },
    propertyGenes: {
      speed: 170,
      damage: 34,
      dot: 6,
      knockback: 5,
      aoe: 4,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 7,
      trailSize: 4,
      aura: true,
      auraSize: 26,
      auraIntensity: 0.65,
      impactParticles: 28,
      impactType: 'spark',
      sizeMultiplier: 1.12,
    },
    rarity: 'unusual'
  },

  frost: {
    name: 'Frost',
    color: { r: 150, g: 200, b: 220 },
    secondaryColor: { r: 180, g: 220, b: 240 },
    accentColor: { r: 120, g: 180, b: 200 },
    propertyGenes: {
      speed: 210,
      damage: 18,
      slowing: 7,
      piercing: 4,
      chaining: 2,
    },
    visualEffects: {
      trail: true,
      trailType: 'trail',
      trailDensity: 5,
      trailSize: 2,
      aura: true,
      auraSize: 22,
      auraIntensity: 0.48,
      impactParticles: 18,
      impactType: 'spark',
      shimmer: true,
      sizeMultiplier: 0.98,
    },
    rarity: 'unusual'
  },

  tundra: {
    name: 'Tundra',
    color: { r: 180, g: 210, b: 220 },
    secondaryColor: { r: 200, g: 225, b: 235 },
    accentColor: { r: 160, g: 190, b: 200 },
    propertyGenes: {
      speed: 190,
      damage: 20,
      slowing: 8,
      wave: 4,
      aoe: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 6,
      trailSize: 2,
      aura: true,
      auraSize: 24,
      auraIntensity: 0.42,
      impactParticles: 16,
      impactType: 'swirl',
      wispy: true,
      sizeMultiplier: 0.94,
    },
    rarity: 'unusual'
  },

  bubble: {
    name: 'Bubble',
    color: { r: 200, g: 230, b: 255 },
    secondaryColor: { r: 220, g: 245, b: 255 },
    accentColor: { r: 180, g: 200, b: 240 },
    propertyGenes: {
      speed: 260,
      damage: 14,
      wave: 7,
      splitting: 4,
      knockback: 2,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 8,
      trailSize: 2,
      aura: true,
      auraSize: 25,
      auraIntensity: 0.4,
      impactParticles: 16,
      impactType: 'swirl',
      wispy: true,
      sizeMultiplier: 0.88,
    },
    rarity: 'unusual'
  },

  web: {
    name: 'Web',
    color: { r: 180, g: 160, b: 140 },
    secondaryColor: { r: 200, g: 180, b: 160 },
    accentColor: { r: 160, g: 140, b: 120 },
    propertyGenes: {
      speed: 200,
      damage: 16,
      chaining: 7,
      slowing: 5,
      aoe: 2,
    },
    visualEffects: {
      trail: true,
      trailType: 'trail',
      trailDensity: 7,
      trailSize: 1,
      aura: true,
      auraSize: 20,
      auraIntensity: 0.35,
      impactParticles: 14,
      impactType: 'swirl',
      sizeMultiplier: 0.9,
    },
    rarity: 'unusual'
  },
};

export default UNUSUAL_ELEMENTS;

