export const RARE_ELEMENTS = {
  virus: {
    name: 'Virus',
    color: { r: 100, g: 255, b: 80 },
    secondaryColor: { r: 120, g: 255, b: 100 },
    accentColor: { r: 80, g: 220, b: 60 },
    propertyGenes: {
      speed: 280,
      damage: 26,
      dot: 8,
      chaining: 5,
      splitting: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 8,
      trailSize: 2,
      aura: true,
      auraSize: 26,
      auraIntensity: 0.62,
      impactParticles: 26,
      impactType: 'spark',
      randomColors: true,
      sizeMultiplier: 1.04,
    },
    rarity: 'rare'
  },

  venom: {
    name: 'Venom',
    color: { r: 150, g: 200, b: 80 },
    secondaryColor: { r: 180, g: 220, b: 100 },
    accentColor: { r: 120, g: 180, b: 60 },
    propertyGenes: {
      speed: 240,
      damage: 24,
      dot: 9,
      piercing: 5,
      homing: 4,
    },
    visualEffects: {
      trail: true,
      trailType: 'smoke',
      trailDensity: 7,
      trailSize: 3,
      aura: true,
      auraSize: 24,
      auraIntensity: 0.58,
      impactParticles: 24,
      impactType: 'swirl',
      wispy: true,
      sizeMultiplier: 1.05,
    },
    rarity: 'rare'
  },

  acid: {
    name: 'Acid',
    color: { r: 200, g: 220, b: 80 },
    secondaryColor: { r: 220, g: 240, b: 100 },
    accentColor: { r: 180, g: 200, b: 60 },
    propertyGenes: {
      speed: 260,
      damage: 28,
      dot: 7,
      aoe: 5,
      piercing: 4,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 8,
      trailSize: 2,
      aura: true,
      auraSize: 25,
      auraIntensity: 0.65,
      impactParticles: 28,
      impactType: 'spark',
      sizeMultiplier: 1.06,
    },
    rarity: 'rare'
  },

  glow: {
    name: 'Glow',
    color: { r: 255, g: 220, b: 100 },
    secondaryColor: { r: 255, g: 240, b: 140 },
    accentColor: { r: 255, g: 200, b: 80 },
    propertyGenes: {
      speed: 300,
      damage: 22,
      chaining: 6,
      wave: 6,
      aoe: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'beam',
      trailDensity: 9,
      trailSize: 2,
      aura: true,
      auraSize: 28,
      auraIntensity: 0.72,
      impactParticles: 24,
      impactType: 'spark',
      shimmer: true,
      sizeMultiplier: 1.0,
    },
    rarity: 'rare'
  },

  static: {
    name: 'Static',
    color: { r: 220, g: 180, b: 255 },
    secondaryColor: { r: 240, g: 200, b: 255 },
    accentColor: { r: 200, g: 160, b: 240 },
    propertyGenes: {
      speed: 320,
      damage: 20,
      chaining: 8,
      wave: 5,
      knockback: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 10,
      trailSize: 1,
      aura: true,
      auraSize: 22,
      auraIntensity: 0.6,
      impactParticles: 20,
      impactType: 'spark',
      chaotic: true,
      sizeMultiplier: 0.96,
    },
    rarity: 'rare'
  },

  magnetism: {
    name: 'Magnetism',
    color: { r: 180, g: 100, b: 220 },
    secondaryColor: { r: 200, g: 120, b: 240 },
    accentColor: { r: 160, g: 80, b: 200 },
    propertyGenes: {
      speed: 230,
      damage: 24,
      homing: 8,
      aoe: 5,
      knockback: 4,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 7,
      trailSize: 2,
      aura: true,
      auraSize: 27,
      auraIntensity: 0.68,
      impactParticles: 26,
      impactType: 'swirl',
      sizeMultiplier: 1.08,
    },
    rarity: 'rare'
  },

  mercury: {
    name: 'Mercury',
    color: { r: 200, g: 200, b: 220 },
    secondaryColor: { r: 220, g: 220, b: 240 },
    accentColor: { r: 180, g: 180, b: 200 },
    propertyGenes: {
      speed: 310,
      damage: 18,
      homing: 7,
      wave: 5,
      chaining: 4,
      piercing: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'beam',
      trailDensity: 8,
      trailSize: 1,
      aura: true,
      auraSize: 20,
      auraIntensity: 0.55,
      impactParticles: 18,
      impactType: 'spark',
      shimmer: true,
      sizeMultiplier: 0.94,
    },
    rarity: 'rare'
  },

  plasma: {
    name: 'Plasma',
    color: { r: 255, g: 150, b: 200 },
    secondaryColor: { r: 255, g: 180, b: 220 },
    accentColor: { r: 255, g: 120, b: 180 },
    propertyGenes: {
      speed: 290,
      damage: 30,
      dot: 6,
      aoe: 6,
      wave: 4,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 9,
      trailSize: 3,
      aura: true,
      auraSize: 26,
      auraIntensity: 0.7,
      impactParticles: 30,
      impactType: 'spark',
      sizeMultiplier: 1.1,
    },
    rarity: 'rare'
  },

  emberheart: {
    name: 'Emberheart',
    color: { r: 255, g: 100, b: 60 },
    secondaryColor: { r: 255, g: 140, b: 80 },
    accentColor: { r: 255, g: 80, b: 40 },
    propertyGenes: {
      speed: 250,
      damage: 32,
      dot: 7,
      knockback: 5,
      lifesteal: 4,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 8,
      trailSize: 4,
      aura: true,
      auraSize: 28,
      auraIntensity: 0.75,
      impactParticles: 32,
      impactType: 'spark',
      sizeMultiplier: 1.12,
    },
    rarity: 'rare'
  },

  velvet: {
    name: 'Velvet',
    color: { r: 100, g: 40, b: 120 },
    secondaryColor: { r: 120, g: 60, b: 140 },
    accentColor: { r: 80, g: 20, b: 100 },
    propertyGenes: {
      speed: 220,
      damage: 26,
      slowing: 7,
      homing: 5,
      aoe: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'smoke',
      trailDensity: 6,
      trailSize: 2,
      aura: true,
      auraSize: 24,
      auraIntensity: 0.62,
      impactParticles: 22,
      impactType: 'swirl',
      wispy: true,
      sizeMultiplier: 1.02,
    },
    rarity: 'rare'
  },

  mycelium: {
    name: 'Mycelium',
    color: { r: 140, g: 180, b: 100 },
    secondaryColor: { r: 160, g: 200, b: 120 },
    accentColor: { r: 120, g: 160, b: 80 },
    propertyGenes: {
      speed: 190,
      damage: 22,
      dot: 8,
      aoe: 6,
      chaining: 4,
      wave: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'aura',
      trailDensity: 7,
      trailSize: 2,
      aura: true,
      auraSize: 26,
      auraIntensity: 0.58,
      impactParticles: 24,
      impactType: 'aura',
      sizeMultiplier: 1.05,
    },
    rarity: 'rare'
  },

  chime: {
    name: 'Chime',
    color: { r: 200, g: 220, b: 255 },
    secondaryColor: { r: 220, g: 240, b: 255 },
    accentColor: { r: 180, g: 200, b: 240 },
    propertyGenes: {
      speed: 270,
      damage: 18,
      wave: 8,
      chaining: 6,
      splitting: 4,
      spiral: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 9,
      trailSize: 1,
      aura: true,
      auraSize: 25,
      auraIntensity: 0.6,
      impactParticles: 20,
      impactType: 'swirl',
      shimmer: true,
      sizeMultiplier: 0.98,
    },
    rarity: 'rare'
  },
};

export default RARE_ELEMENTS;

