export const EXOTIC_ELEMENTS = {
  arcane: {
    name: 'Arcane',
    color: { r: 200, g: 120, b: 255 },
    secondaryColor: { r: 220, g: 150, b: 255 },
    accentColor: { r: 180, g: 100, b: 240 },
    propertyGenes: {
      speed: 270,
      damage: 26,
      chaining: 7,
      wave: 6,
      aoe: 5,
      homing: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 9,
      trailSize: 2,
      aura: true,
      auraSize: 30,
      auraIntensity: 0.68,
      impactParticles: 28,
      impactType: 'swirl',
      swirl: true,
      sizeMultiplier: 1.06,
    },
    rarity: 'exotic'
  },

  shadow: {
    name: 'Shadow',
    color: { r: 80, g: 60, b: 100 },
    secondaryColor: { r: 100, g: 80, b: 120 },
    accentColor: { r: 60, g: 40, b: 80 },
    propertyGenes: {
      speed: 290,
      damage: 26,
      homing: 7,
      piercing: 6,
      dot: 4,
      chaining: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'smoke',
      trailDensity: 8,
      trailSize: 2,
      aura: true,
      auraSize: 26,
      auraIntensity: 0.62,
      impactParticles: 24,
      impactType: 'swirl',
      wispy: true,
      sizeMultiplier: 1.04,
    },
    rarity: 'exotic'
  },

  light: {
    name: 'Light',
    color: { r: 255, g: 240, b: 120 },
    secondaryColor: { r: 255, g: 255, b: 150 },
    accentColor: { r: 255, g: 220, b: 80 },
    propertyGenes: {
      speed: 310,
      damage: 24,
      piercing: 8,
      chaining: 6,
      aoe: 4,
      homing: 2,
    },
    visualEffects: {
      trail: true,
      trailType: 'beam',
      trailDensity: 10,
      trailSize: 2,
      aura: true,
      auraSize: 28,
      auraIntensity: 0.72,
      impactParticles: 26,
      impactType: 'spark',
      beam: true,
      sizeMultiplier: 1.04,
    },
    rarity: 'exotic'
  },

  mirage: {
    name: 'Mirage',
    color: { r: 200, g: 180, b: 220 },
    secondaryColor: { r: 220, g: 200, b: 240 },
    accentColor: { r: 180, g: 160, b: 200 },
    propertyGenes: {
      speed: 300,
      damage: 20,
      homing: 7,
      wave: 7,
      splitting: 4,
      chaining: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 10,
      trailSize: 2,
      aura: true,
      auraSize: 28,
      auraIntensity: 0.65,
      impactParticles: 24,
      impactType: 'swirl',
      shimmer: true,
      sizeMultiplier: 1.02,
    },
    rarity: 'exotic'
  },

  glitch: {
    name: 'Glitch',
    color: { r: 150, g: 255, b: 200 },
    secondaryColor: { r: 180, g: 255, b: 220 },
    accentColor: { r: 120, g: 230, b: 180 },
    propertyGenes: {
      speed: 320,
      damage: 22,
      chaining: 7,
      wave: 6,
      piercing: 4,
      splitting: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 11,
      trailSize: 2,
      aura: true,
      auraSize: 24,
      auraIntensity: 0.64,
      impactParticles: 26,
      impactType: 'spark',
      chaotic: true,
      randomColors: true,
      sizeMultiplier: 1.0,
    },
    rarity: 'exotic'
  },

  hologram: {
    name: 'Hologram',
    color: { r: 150, g: 200, b: 255 },
    secondaryColor: { r: 180, g: 220, b: 255 },
    accentColor: { r: 120, g: 180, b: 240 },
    propertyGenes: {
      speed: 290,
      damage: 24,
      homing: 6,
      chaining: 6,
      aoe: 5,
      wave: 4,
    },
    visualEffects: {
      trail: true,
      trailType: 'beam',
      trailDensity: 9,
      trailSize: 2,
      aura: true,
      auraSize: 26,
      auraIntensity: 0.67,
      impactParticles: 24,
      impactType: 'spark',
      shimmer: true,
      sizeMultiplier: 1.05,
    },
    rarity: 'exotic'
  },

  melody: {
    name: 'Melody',
    color: { r: 200, g: 100, b: 200 },
    secondaryColor: { r: 220, g: 120, b: 220 },
    accentColor: { r: 180, g: 80, b: 180 },
    propertyGenes: {
      speed: 280,
      damage: 20,
      chaining: 8,
      wave: 7,
      aoe: 5,
      splitting: 2,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 10,
      trailSize: 2,
      aura: true,
      auraSize: 28,
      auraIntensity: 0.68,
      impactParticles: 26,
      impactType: 'swirl',
      swirl: true,
      sizeMultiplier: 1.04,
    },
    rarity: 'exotic'
  },

  stardust: {
    name: 'Stardust',
    color: { r: 255, g: 220, b: 150 },
    secondaryColor: { r: 255, g: 240, b: 180 },
    accentColor: { r: 255, g: 200, b: 120 },
    propertyGenes: {
      speed: 280,
      damage: 26,
      wave: 7,
      splitting: 5,
      lifesteal: 5,
      chaining: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 10,
      trailSize: 2,
      aura: true,
      auraSize: 30,
      auraIntensity: 0.72,
      impactParticles: 28,
      impactType: 'spark',
      randomColors: true,
      sizeMultiplier: 1.07,
    },
    rarity: 'exotic'
  },

  solar: {
    name: 'Solar',
    color: { r: 255, g: 180, b: 60 },
    secondaryColor: { r: 255, g: 200, b: 100 },
    accentColor: { r: 255, g: 160, b: 40 },
    propertyGenes: {
      speed: 300,
      damage: 32,
      aoe: 7,
      dot: 6,
      piercing: 4,
      knockback: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 10,
      trailSize: 3,
      aura: true,
      auraSize: 34,
      auraIntensity: 0.82,
      impactParticles: 32,
      impactType: 'spark',
      beam: true,
      sizeMultiplier: 1.14,
    },
    rarity: 'exotic'
  },

  lunar: {
    name: 'Lunar',
    color: { r: 200, g: 220, b: 255 },
    secondaryColor: { r: 220, g: 240, b: 255 },
    accentColor: { r: 180, g: 200, b: 240 },
    propertyGenes: {
      speed: 270,
      damage: 22,
      homing: 8,
      slowing: 7,
      wave: 6,
      spiral: 4,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 9,
      trailSize: 2,
      aura: true,
      auraSize: 32,
      auraIntensity: 0.68,
      impactParticles: 26,
      impactType: 'swirl',
      wispy: true,
      shimmer: true,
      sizeMultiplier: 1.05,
    },
    rarity: 'exotic'
  },

  memory: {
    name: 'Memory',
    color: { r: 180, g: 160, b: 200 },
    secondaryColor: { r: 200, g: 180, b: 220 },
    accentColor: { r: 160, g: 140, b: 180 },
    propertyGenes: {
      speed: 260,
      damage: 24,
      homing: 7,
      chaining: 6,
      aoe: 4,
      wave: 5,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 8,
      trailSize: 2,
      aura: true,
      auraSize: 27,
      auraIntensity: 0.64,
      impactParticles: 24,
      impactType: 'swirl',
      sizeMultiplier: 1.03,
    },
    rarity: 'exotic'
  },

  emotion: {
    name: 'Emotion',
    color: { r: 255, g: 100, b: 150 },
    secondaryColor: { r: 255, g: 130, b: 170 },
    accentColor: { r: 255, g: 80, b: 130 },
    propertyGenes: {
      speed: 270,
      damage: 28,
      wave: 7,
      chaining: 6,
      aoe: 5,
      splitting: 3,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 9,
      trailSize: 2,
      aura: true,
      auraSize: 29,
      auraIntensity: 0.7,
      impactParticles: 28,
      impactType: 'spark',
      randomColors: true,
      sizeMultiplier: 1.08,
    },
    rarity: 'exotic'
  },
};

export default EXOTIC_ELEMENTS;

