export const MYTHIC_ELEMENTS = {
  theOriginOfAllThatIs: {
    name: 'The Origin of All That Is',
    color: { r: 255, g: 255, b: 230 },
    secondaryColor: { r: 255, g: 223, b: 186 },
    accentColor: { r: 207, g: 181, b: 255 },
    propertyGenes: {
      speed: 320,
      damage: 35,
      aoe: 8,
      splitting: 6,
      wave: 7,
      lifesteal: 5,
    },
    visualEffects: {
      trail: true,
      trailType: 'beam',
      trailDensity: 12,
      trailSize: 4,
      aura: true,
      auraSize: 50,
      auraIntensity: 0.9,
      impactParticles: 50,
      impactType: 'spark',
      beam: true,
      shimmer: true,
      sizeMultiplier: 1.3,
    },
    rarity: 'mythic'
  },
  theEndOfAllThatWas: {
    name: 'The End of All That Was',
    color: { r: 40, g: 10, b: 50 },
    secondaryColor: { r: 90, g: 20, b: 30 },
    accentColor: { r: 150, g: 50, b: 80 },
    propertyGenes: {
      speed: 280,
      damage: 45,
      dot: 10,
      homing: 6,
      piercing: 8,
    },
    visualEffects: {
      trail: true,
      trailType: 'smoke',
      trailDensity: 10,
      trailSize: 5,
      aura: true,
      auraSize: 45,
      auraIntensity: 0.8,
      impactParticles: 40,
      impactType: 'swirl',
      wispy: true,
      sizeMultiplier: 1.2,
    },
    rarity: 'mythic'
  },
  absoluteNothingness: {
    name: 'Absolute Nothingness',
    color: { r: 5, g: 5, b: 10 },
    secondaryColor: { r: 2, g: 2, b: 2 },
    accentColor: { r: 20, g: 20, b: 35 },
    propertyGenes: {
      speed: 400,
      damage: 30,
      slowing: 9,
      piercing: 10,
      spiral: 8,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 15,
      trailSize: 3,
      aura: true,
      auraSize: 40,
      auraIntensity: 1.0,
      impactParticles: 20,
      impactType: 'swirl',
      sizeMultiplier: 1.0,
    },
    rarity: 'mythic'
  },
  theLivingUniverse: {
    name: 'The Living Universe',
    color: { r: 180, g: 100, b: 255 },
    secondaryColor: { r: 100, g: 220, b: 255 },
    accentColor: { r: 255, g: 150, b: 200 },
    propertyGenes: {
      speed: 300,
      damage: 28,
      chaining: 9,
      wave: 8,
      spiral: 6,
      aoe: 5,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 11,
      trailSize: 3,
      aura: true,
      auraSize: 38,
      auraIntensity: 0.75,
      impactParticles: 35,
      impactType: 'spark',
      chaotic: true,
      randomColors: true,
      sizeMultiplier: 1.15,
    },
    rarity: 'mythic'
  },
  eternalDreaming: {
    name: 'Eternal Dreaming',
    color: { r: 255, g: 179, b: 248 },
    secondaryColor: { r: 179, g: 236, b: 255 },
    accentColor: { r: 255, g: 252, b: 179 },
    propertyGenes: {
      speed: 260,
      damage: 25,
      homing: 9,
      slowing: 8,
      wave: 9,
      spiral: 5,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 9,
      trailSize: 3,
      aura: true,
      auraSize: 42,
      auraIntensity: 0.6,
      impactParticles: 30,
      impactType: 'swirl',
      wispy: true,
      shimmer: true,
      sizeMultiplier: 1.1,
    },
    rarity: 'mythic'
  },
  theUnnamedSource: {
    name: 'The Unnamed Source',
    color: { r: 200, g: 240, b: 255 },
    secondaryColor: { r: 255, g: 255, b: 255 },
    accentColor: { r: 150, g: 200, b: 255 },
    propertyGenes: {
      speed: 380,
      damage: 32,
      piercing: 9,
      chaining: 7,
      knockback: 6,
    },
    visualEffects: {
      trail: true,
      trailType: 'beam',
      trailDensity: 14,
      trailSize: 3,
      aura: true,
      auraSize: 35,
      auraIntensity: 0.85,
      impactParticles: 38,
      impactType: 'spark',
      beam: true,
      sizeMultiplier: 1.05,
    },
    rarity: 'mythic'
  },
  infiniteSymphony: {
    name: 'Infinite Symphony',
    color: { r: 255, g: 100, b: 180 },
    secondaryColor: { r: 100, g: 180, b: 255 },
    accentColor: { r: 180, g: 255, b: 100 },
    propertyGenes: {
      speed: 290,
      damage: 26,
      wave: 10,
      chaining: 8,
      aoe: 7,
      spiral: 7,
    },
    visualEffects: {
      trail: true,
      trailType: 'swirl',
      trailDensity: 12,
      trailSize: 2,
      aura: true,
      auraSize: 40,
      auraIntensity: 0.7,
      impactParticles: 33,
      impactType: 'swirl',
      swirl: true,
      randomColors: true,
      sizeMultiplier: 1.1,
    },
    rarity: 'mythic'
  },
  primordialWill: {
    name: 'Primordial Will',
    color: { r: 255, g: 80, b: 30 },
    secondaryColor: { r: 200, g: 40, b: 10 },
    accentColor: { r: 255, g: 150, b: 50 },
    propertyGenes: {
      speed: 270,
      damage: 42,
      knockback: 10,
      homing: 8,
      aoe: 6,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 10,
      trailSize: 5,
      aura: true,
      auraSize: 48,
      auraIntensity: 0.9,
      impactParticles: 45,
      impactType: 'spark',
      sizeMultiplier: 1.25,
    },
    rarity: 'mythic'
  },
  objectiveTruth: {
    name: 'Objective Truth',
    color: { r: 220, g: 230, b: 255 },
    secondaryColor: { r: 255, g: 255, b: 255 },
    accentColor: { r: 180, g: 240, b: 255 },
    propertyGenes: {
      speed: 350,
      damage: 30,
      piercing: 10,
      splitting: 8,
      homing: 5,
    },
    visualEffects: {
      trail: true,
      trailType: 'beam',
      trailDensity: 10,
      trailSize: 2,
      aura: true,
      auraSize: 30,
      auraIntensity: 0.8,
      impactParticles: 30,
      impactType: 'spark',
      shimmer: true,
      beam: true,
      sizeMultiplier: 0.95,
    },
    rarity: 'mythic'
  },
  coreOfMythology: {
    name: 'Core of Mythology',
    color: { r: 255, g: 215, b: 0 },
    secondaryColor: { r: 255, g: 250, b: 205 },
    accentColor: { r: 255, g: 165, b: 0 },
    propertyGenes: {
      speed: 310,
      damage: 33,
      aoe: 7,
      lifesteal: 7,
      homing: 7,
      wave: 5,
    },
    visualEffects: {
      trail: true,
      trailType: 'spark',
      trailDensity: 11,
      trailSize: 3,
      aura: true,
      auraSize: 44,
      auraIntensity: 0.95,
      impactParticles: 42,
      impactType: 'spark',
      swirl: true,
      shimmer: true,
      sizeMultiplier: 1.2,
    },
    rarity: 'mythic'
  },
};

